#!/bin/bash

echo "Let's do some simple additions😊"
sleep 1
echo "Provide two numbers and i will sum it for you. Easy right?"
echo "Input Number_1"
read num1
sleep 1
echo "Input Number_2"
read num2

num3=$(( num1 + num2 ))

if [ $num3 -gt 20 ];
then
	echo "Weldone"
else
	echo "Do more"
	read num4
	echo $(( $num4 + $num3 ))
fi

